### ISSUE TITLE
请求失败,调试很久没有搞定

### ISSUE THREAD

**Issue by BigLight-H** [woodylan/go-websocket#11]
显示这些错误
服务器启动成功，端口号：6000
2021-12-09 00:03:10.941497 I | http: panic serving 127.0.0.1:44690: crypto/aes: invalid key size 0
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc0002b8000)
        /home/travis/.gimme/versions/go1.13.15.linux.amd64/src/net/http/server.go:1795 +0x139
panic(0xb23300, 0x12432a0)
        /home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/panic.go:679 +0x1b2
go-websocket/tools/util.GenClientId(0xc0000cba00, 0xc2e91a)
        /home/travis/gopath/src/github.com/woodylan/go-websocket/tools/util/util.go:25 +0x164
go-websocket/servers.(*Controller).Run(0x1242090, 0xd2a780, 0xc0000c6380, 0xc0000cba00)
        /home/travis/gopath/src/github.com/woodylan/go-websocket/servers/connect.go:50 +0x20d
net/http.HandlerFunc.ServeHTTP(0xc00028e390, 0xd2a780, 0xc0000c6380, 0xc0000cba00)
        /home/travis/.gimme/versions/go1.13.15.linux.amd64/src/net/http/server.go:2036 +0x44
net/http.(*ServeMux).ServeHTTP(0x1225380, 0xd2a780, 0xc0000c6380, 0xc0000cba00)
        /home/travis/.gimme/versions/go1.13.15.linux.amd64/src/net/http/server.go:2416 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0000c62a0, 0xd2a780, 0xc0000c6380, 0xc0000cba00)
        /home/travis/.gimme/versions/go1.13.15.linux.amd64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc0002b8000, 0xd2be40, 0xc00024cac0)
        /home/travis/.gimme/versions/go1.13.15.linux.amd64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.13.15.linux.amd64/src/net/http/server.go:2957 +0x384

**Comment by Hhhha** [comment]
app.ini 里面的 CryptoKey字段长度不符合要求 只允许16、24、32字节长度
